# Python script to get on-target scores using CRISPOR
# Placeholder for the actual CRISPOR CLI command or Python function
# Replace 'crispor_function' with the actual function from CRISPOR's Python module

import pandas as pd

# Load sgRNA sequences from the file generated by the R script
sgRNA_sequences = pd.read_csv('sgRNAs.txt', header=None)

# Function to get on-target scores (this is a placeholder)
def get_on_target_scores(sgRNA_sequences):
    # Placeholder for the actual scoring function
    # Replace this with the actual code to get scores from CRISPOR
    scores = {}
    for sgRNA in sgRNA_sequences[0]:
        scores[sgRNA] = crispor_function(sgRNA)
    return scores

# Get the scores
on_target_scores = get_on_target_scores(sgRNA_sequences)

# Save the scores to a CSV file for use in R
on_target_scores_df = pd.DataFrame(list(on_target_scores.items()), columns=['sgRNA', 'score'])
on_target_scores_df.to_csv('onTargetScores.csv', index=False)
